const data = [
  { input: 'au small finance bank', output: 'aus' },
  { input: 'aus', output: 'aus' },
  { input: 'au small finance bank limited', output: 'aus' },
  { input: 'au small', output: 'aus' },
  { input: 'au small finance', output: 'aus' },
  { input: 'au', output: 'aus' },
  { input: 'aublr', output: 'aus' },
  { input: 'axis bank', output: 'axis' },
  { input: 'axis', output: 'axis' },
  { input: 'utibr', output: 'axis' },
  { input: 'axisc', output: 'axisc' },
  { input: 'axis corporate', output: 'axisc' },
  { input: 'utibc', output: 'axisc' },
  { input: 'bandhan bank', output: 'bdnc' },
  { input: 'bandhan', output: 'bdnc' },
  { input: 'bdnc', output: 'bdnc' },
  { input: 'bandhan corporate', output: 'bdnc' },
  { input: 'bdblc', output: 'bdnc' },
  { input: 'bdnr', output: 'bdnr' },
  { input: 'bandhan retail', output: 'bdnr' },
  { input: 'bdblr', output: 'bdnr' },
  { input: 'bobc', output: 'bobc' },
  { input: 'bank of baroda', output: 'bobc' },
  { input: 'barbc', output: 'bobc' },
  { input: 'bobr', output: 'bobr' },
  { input: 'barbr', output: 'bobr' },
  { input: 'boi', output: 'boi' },
  { input: 'bank of india', output: 'boi' },
  { input: 'bkidr', output: 'boi' },
  { input: 'bkidc', output: 'boi' },
  { input: 'bom', output: 'bom' },
  { input: 'bank of maharashtra', output: 'bom' },
  { input: 'mahbr', output: 'bom' },
  { input: 'canara', output: 'canara' },
  { input: 'canara bank', output: 'canara' },
  { input: 'cnrbr', output: 'canara' },
  { input: 'central bank of india', output: 'cbi' },
  { input: 'cbi', output: 'cbi' },
  { input: 'cbinr', output: 'cbi' },
  { input: 'csb bank', output: 'csb' },
  { input: 'csb', output: 'csb' },
  { input: 'catholic syrian bank limited', output: 'csb' },
  { input: 'catholic syrian bank', output: 'csb' },
  { input: 'csbkr', output: 'csb' },
  { input: 'city union bank', output: 'cub' },
  { input: 'cub', output: 'cub' },
  { input: 'ciubr', output: 'cub' },
  { input: 'ciubc', output: 'cub' },
  { input: 'dbs', output: 'dbs' },
  { input: 'dbs bank', output: 'dbs' },
  { input: 'digibank', output: 'dbs' },
  { input: 'dbssr', output: 'dbs' },
  { input: 'deutsche', output: 'deutsche' },
  { input: 'deutsche bank', output: 'deutsche' },
  { input: 'deutr', output: 'deutsche' },
  { input: 'dhanlakshmi', output: 'dhanlakshmi' },
  { input: 'dhanlakshmi bank', output: 'dhanlakshmi' },
  { input: 'dlxbr', output: 'dhanlakshmi' },
  { input: 'dlxbc', output: 'dhanlakshmi' },
  { input: 'equitas small finance bank', output: 'equitas' },
  { input: 'equitas', output: 'equitas' },
  { input: 'equitas small finance', output: 'equitas' },
  { input: 'equitas bank', output: 'equitas' },
  { input: 'esfbr', output: 'equitas' },
  { input: 'federal bank', output: 'federal' },
  { input: 'federal', output: 'federal' },
  { input: 'fdrlr', output: 'federal' },
  { input: 'hdfc', output: 'hdfc' },
  { input: 'hdfc bank', output: 'hdfc' },
  { input: 'hdfcr', output: 'hdfc' },
  { input: 'hdfcc', output: 'hdfc' },
  { input: 'icici', output: 'icici' },
  { input: 'icici bank', output: 'icici' },
  { input: 'icicr', output: 'icici' },
  { input: 'icicc', output: 'icici' },
  { input: 'idfc', output: 'idfc' },
  { input: 'idfc bank', output: 'idfc' },
  { input: 'idfc first bank', output: 'idfc' },
  { input: 'idfbr', output: 'idfc' },
  { input: 'indian', output: 'indian' },
  { input: 'indian bank', output: 'indian' },
  { input: 'idibr', output: 'indian' },
  { input: 'indusind', output: 'indusind' },
  { input: 'indusind bank', output: 'indusind' },
  { input: 'indbr', output: 'indusind' },
  { input: 'iob', output: 'iob' },
  { input: 'iob bank', output: 'iob' },
  { input: 'indian overseas bank', output: 'iob' },
  { input: 'indian overseas bank', output: 'iob' },
  { input: 'iobar', output: 'iob' },
  { input: 'iobc', output: 'iobc' },
  { input: 'iob corporate', output: 'iobc' },
  { input: 'indian overseas corporate', output: 'iobc' },
  { input: 'indian overseas bank corporate', output: 'iobc' },
  { input: 'iobac', output: 'iobc' },
  { input: 'jkb', output: 'jkb' },
  { input: 'jammu & kashmir bank', output: 'jkb' },
  { input: 'jammu and kashmir bank', output: 'jkb' },
  { input: 'j&k bank', output: 'jkb' },
  { input: 'jakar', output: 'jkb' },
  { input: 'karnataka', output: 'karnatka' },
  { input: 'karnataka bank', output: 'karnatka' },
  { input: 'karnatka', output: 'karnatka' },
  { input: 'karnatka bank', output: 'karnatka' },
  { input: 'karbr', output: 'karnatka' },
  { input: 'karur', output: 'karur' },
  { input: 'karur bank', output: 'karur' },
  { input: 'karur vysya bank', output: 'karur' },
  { input: 'karur vysya', output: 'karur' },
  { input: 'kvblr', output: 'karur' },
  { input: 'kotak', output: 'kotak' },
  { input: 'kotak bank', output: 'kotak' },
  { input: 'kkbkr', output: 'kotak' },
  { input: 'lvbc', output: 'lvbc' },
  { input: 'lvb corporate', output: 'lvbc' },
  { input: 'lavbc', output: 'lvbc' },
  { input: 'lvbr', output: 'lvbr' },
  { input: 'lvb retail', output: 'lvbr' },
  { input: 'lavbr', output: 'lvbr' },
  { input: 'pnbc', output: 'pnbc' },
  { input: 'punjab national bank corporate', output: 'pnbc' },
  { input: 'pnb', output: 'pnbc' },
  { input: 'punjab national bank', output: 'pnbc' },
  { input: 'punbc', output: 'pnbc' },
  { input: 'pnbr', output: 'pnbr' },
  { input: 'punjab national bank retail', output: 'pnbr' },
  { input: 'punbr', output: 'pnbr' },
  { input: 'rbl', output: 'rbl' },
  { input: 'ratnakar bank', output: 'rbl' },
  { input: 'rbl bank', output: 'rbl' },
  { input: 'ratnr', output: 'rbl' },
  { input: 'rbl corporate', output: 'rblc' },
  { input: 'rblc', output: 'rblc' },
  { input: 'ratnc', output: 'rblc' },
  { input: 'saraswat', output: 'saraswat' },
  { input: 'saraswat bank', output: 'saraswat' },
  { input: 'srcbr', output: 'saraswat' },
  { input: 'sbi', output: 'sbi' },
  { input: 'state bank of india', output: 'sbi' },
  { input: 'sbinr', output: 'sbi' },
  { input: 'sbic', output: 'sbic' },
  { input: 'sbi corporate', output: 'sbic' },
  { input: 'state bank of india corporate', output: 'sbic' },
  { input: 'sbinc', output: 'sbic' },
  { input: 'scb', output: 'scb' },
  { input: 'standard chartered', output: 'scb' },
  { input: 'standard chartered bank', output: 'scb' },
  { input: 'scblr', output: 'scb' },
  { input: 'shivalik', output: 'shivalik' },
  { input: 'shivalik bank', output: 'shivalik' },
  { input: 'smcbr', output: 'shivalik' },
  { input: 'sib', output: 'sib' },
  { input: 'south indian bank', output: 'sib' },
  { input: 'siblr', output: 'sib' },
  { input: 'sur', output: 'sur' },
  { input: 'sur bank', output: 'sur' },
  { input: 'tamcop', output: 'tamcop' },
  { input: 'tamcop bank', output: 'tamcop' },
  { input: 'tammerc', output: 'tammerc' },
  { input: 'tammerc bank', output: 'tammerc' },
  { input: 'uco', output: 'uco' },
  { input: 'uco bank', output: 'uco' },
  { input: 'united commercial bank', output: 'uco' },
  { input: 'ucbar', output: 'uco' },
  { input: 'ucbac', output: 'uco' },
  { input: 'union', output: 'union' },
  { input: 'union bank', output: 'union' },
  { input: 'ubinr', output: 'union' },
  { input: 'ubinc', output: 'union' },
  { input: 'utk', output: 'utk' },
  { input: 'utk bank', output: 'utk' },
  { input: 'utkarsh small finance bank', output: 'utk' },
  { input: 'utkarsh small finance', output: 'utk' },
  { input: 'utksr', output: 'utk' },
  { input: 'yes', output: 'yes' },
  { input: 'yes bank', output: 'yes' },
  { input: 'yesbc', output: 'yes' },
  { input: 'yesbr', output: 'yes' },
];

const map = {};

data.forEach(element => {
  if (map[element.output] === undefined)
    map[element.output] = [element]
  else
    map[element.output].push(element);
});

console.log(map);